### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by tomdapchai** [Virenbar/discord-emoji-export#14]
I got the token for my account but cannot use as it said "invalid format". I pretty sure it isn't because I can use it for other apps.
Need a quick fix on this.

**Comment by Virenbar** [comment]
I've changed token validation regex.
If it still doesn't work, post the token with some letters replaced by other letters, so it would be invalid.

**Comment by tomdapchai** [comment]
It works now, thank you 👍 
Love this repo haha.
